import { Rubik } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";
import Footer from "@/components/Footer";

const inter = Rubik({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className={inter.className}>
        <div className="flex flex-col  min-h-screen">
          <Nav />
          
          <main className="flex-grow">{children}</main>
          
          <Footer />
        </div>
      </body>
  </html>
  );
}
